### ISSUE TITLE
After setting Alarm and kill the app too will trigger APP STOP pop up at the schedule time

### ISSUE THREAD

**Issue by imran1992** [emekalites/react-native-alarm-notification#18]
`React Native: v 0.57.4`
```
buildToolsVersion = "27.0.3"
minSdkVersion = 19
compileSdkVersion = 27
targetSdkVersion = 26
supportLibVersion = "27.1.1"
```
Tested on 
```
Samsung J7 Prime 
Android 8.1
```
```
import ReactNativeAN from "react-native-alarm-notification";
const fireDate = "21-11-2018 12:33:00";
const alarmNotifData = {
  id: "12345", 
  title: "My Notification Title",
  message: "My Notification Message",
  channel: "islamic1234",
  ticker: "My Notification Ticker",
  auto_cancel: true,
  vibrate: true,
  vibration: 100,
  small_icon: "ic_launcher",
  large_icon: "ic_launcher",
  play_sound: true,
  sound_name: "azan", 
  color: "red",
  schedule_once: true,
  tag: "some_tag",
  fire_date: fireDate, 
  data: { foo: "bar" }
};
```
```
componentWillMount() {
    ReactNativeAN.scheduleAlarm(alarmNotifData);
  }
```

**Comment by kunal886496** [comment]
Agreed

**Comment by emekalites** [comment]
Please I really dont understand his scenario.

**Comment by imran1992** [comment]
When I set alarm. and close the app. I receive POP UP ERROR (APP STOP) at the alarm time.

**Comment by emekalites** [comment]
Can you try the example folder, please and let me know. I am thinking the bug might be from your phone because it works well on my gionee s6s.

**Comment by claude39** [comment]
I have managed to avoid that error when setting an alarm and terminating the app. Here's how I did it.
I called an Intent that starts the app activity when the onReceive method in ANAlarmReceiver.java is being called located at node_module/react-native-alarm-notification.
`public void onReceive(Context context, Intent intent) {
        Intent i = new Intent();
        i.setClassName("com.appName", "com.appName.MainActivity");
        i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        context.startActivity(i);
        
        Intent service = new Intent(context, ANService.class);
        service.putExtras(intent);
        context.startService(service);
    }`

**Comment by haifahrul** [comment]
I think it's not support for Android 8.1. It's force close when notif is triggered

**Comment by kunal886496** [comment]
How to handle this then?

**Comment by haifahrul** [comment]
I have try in Android 7.1.1 and it's work. 
I'm still figuring out this bug and haven't found a solution. Maybe @emekalites can help?

**Comment by kunal886496** [comment]
See the problem  with 8.1 is performance optimization has been the priority.
So some of these things like allowing alarms to wake up screen by some
external apps may nor be allowed

**Comment by kunal886496** [comment]
Not*

**Comment by haifahrul** [comment]
@emekalites I got this error in Android 8, can you check it? please

`FATAL EXCEPTION: main
    Process: com.jasindosyariah, PID: 22190
    java.lang.RuntimeException: Unable to start receiver com.emekalites.react.alarm.notification.ANAlarmReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.jasindosyariah/com.emekalites.react.alarm.notification.ANService (has extras) }: app is in background uid UidRecord{a14d2ec u0a232 RCVR idle change:uncached procs:1 seq(0,0,0)}
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3197)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.jasindosyariah/com.emekalites.react.alarm.notification.ANService (has extras) }: app is in background uid UidRecord{a14d2ec u0a232 RCVR idle change:uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
        at android.app.ContextImpl.startService(ContextImpl.java:1477)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at com.emekalites.react.alarm.notification.ANAlarmReceiver.onReceive(ANAlarmReceiver.java:20)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3190)
        at android.app.ActivityThread.-wrap17(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6518) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) `

**Comment by kunal886496** [comment]
Okay i will let you know.
Positively.

**Comment by emekalites** [comment]
#19

**Comment by VikasTiwari7** [comment]
its not working same thing happen in at end
