### ISSUE TITLE
Alarm crashes when app is closed

### ISSUE THREAD

**Issue by tsanio** [emekalites/react-native-alarm-notification#19]
To reproduce
1. Schedule an alarm.
2. Close the app before the alarm will set off.
This should cause a crash when the alarm is triggered.

This is how errors look like from adb logcat:
```
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.nativetest, PID: 2913
AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.emekalites.react.alarm.notification.ANAlarmReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.nativetest/com.emekalites.react.alarm.notification.ANService (has extras) }: app is in background uid UidRecord{a75b117 u0a85 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3388)
AndroidRuntime:        at android.app.ActivityThread.access$1200(ActivityThread.java:199)
AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.nativetest/com.emekalites.react.alarm.notification.ANService (has extras) }: app is in background uid UidRecord{a75b117 u0a85 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
AndroidRuntime:        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
AndroidRuntime:        at android.app.ContextImpl.startService(ContextImpl.java:1532)
AndroidRuntime:        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
AndroidRuntime:        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
AndroidRuntime:        at com.emekalites.react.alarm.notification.ANAlarmReceiver.onReceive(ANAlarmReceiver.java:20)
AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3379)
AndroidRuntime:        ... 8 more
AudioFlinger: not enough memory for AudioTrack size=131296
AudioFlinger: createRecordTrack_l() initCheck failed -12; no control block?
IAudioFlinger: createRecord returned error -12
AudioRecord: AudioFlinger could not create record track, status: -12
AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -12.
```

One way around seems to be
1. Trigger the alarm once when the app is running.
2. Schedule it again to launch after some time.
2. Close the app before the alarm will set off.
This seems to not cause crash when the alarm is triggered.

**Comment by tsanio** [comment]
I seemed to have set auto_cancel: true. Which seemed cause these behaviors.

**Comment by kunal886496** [comment]
It actually happens and still there is no solution

**Comment by emekalites** [comment]
I tried it and i could not reproduce this issue. Maybe the problem is coming from here **AudioFlinger: not enough memory for AudioTrack size=131296** if so, check the file you are using for your alarm ringtone if its too large or your phone memory is too low. 
Let me know if you've fixed the issue.

**Comment by haifahrul** [comment]
I using android oreo 8.1, and still crash when the alarm is triggered. Any solution?

**Comment by emekalites** [comment]
I'll get an android with oreo 8.1 and test this later this week. @haifahrul

**Comment by haifahrul** [comment]
@emekalites Oke, thank you. Truly I don't understand with Java. But I trying to help and make this project awesome. :+1:

**Comment by haifahrul** [comment]
@emekalites any progress?

**Comment by haifahrul** [comment]
Hi @emekalites any progress?

> I'll get an android with oreo 8.1 and test this later this week. @haifahrul

**Comment by akinmac002** [comment]
I have same problem. Could this problem be due to NotificationChannel ?
https://itnext.io/migrate-your-app-to-android-oreo-e0fa794b1d21
https://stackoverflow.com/questions/43093260/notification-not-showing-in-oreo

**Comment by akinmac002** [comment]
This problem is solved. On: https://github.com/emekalites/react-native-alarm-notification/issues/36
Furkan Atakan BOZKURT
