### ISSUE TITLE
Key alarm_id expected Integer but value was a java.lang.Double.

### ISSUE THREAD

**Issue by EYHN** [emekalites/react-native-alarm-notification#47]
I cannot schedule future reminders, I get error output from logcat.

```
2020-04-05 15:08:40.688 22168-22383/com.timer W/Bundle: Key alarm_id expected Integer but value was a java.lang.Double.  The default value 0 was returned.
2020-04-05 15:08:40.688 22168-22383/com.timer W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
        at android.os.BaseBundle.getInt(BaseBundle.java:1041)
        at android.os.BaseBundle.getInt(BaseBundle.java:1023)
        at com.emekalites.react.alarm.notification.ANModule.scheduleAlarm(ANModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
2020-04-05 15:08:40.689 22168-22383/com.timer E/com.emekalites.react.alarm.notification.ANModule: failed to schedule notification because fire date is missing
```

Here is my code.
```
const alarmNotifData = {
	alarm_id: 12345,
	title: "My Notification Title",
	message: "My Notification Message",
	channel: "my_channel_id",
	small_icon: "ic_launcher"
};
ReactNativeAN.scheduleAlarm({...alarmNotifData, fireDate: ReactNativeAN.parseDate(new Date(endDate.current)) });
```

My package version:
react: 16.11.0
react-native: 0.62.0
react-native-alarm-notification: 1.4.2

**Comment by emekalites** [comment]
install the latest version v1.4.3 and let me if it works.
